сделал 5 заданий 1 урока
js-tasks-ru/jsbasic-20221028_staraurt pull request #2
Opened 2022-11-06 19:33 UTC by Faxajj

2022-11-06 19:34 UTC, jsru commented
Добавляю преподавателя (@koalex) для код-ревью.

2022-11-07 02:28 UTC, koalex requested changes
Исправить замечания в **1-3** и **1-4**

2022-11-07 02:28 UTC, koalex commented on 1-module/3-task/index.js
> +alert( ucFirst("вася") );
Удалить `alert`-ы

2022-11-07 02:28 UTC, koalex commented on 1-module/4-task/index.js
> +  alert( checkSpam ('1xBet') );
Удалить `alert`-ы

2022-11-10 20:25 UTC, jsru commented
Добавляю преподавателя (@koalex) для код-ревью.

2022-11-10 20:32 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @koalex

2022-11-10 20:57 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-11-10 21:06 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-11-11 03:42 UTC, koalex requested changes
Исправить замечание в **2-3**

2022-11-11 03:42 UTC, koalex commented on 2-module/3-task/index.js
> +  read() {
read(a, b) {
     this.a = a;
     this.b = b;
}

2022-11-11 16:02 UTC, jsru commented
Добавляю преподавателя (@koalex) для код-ревью.

2022-11-13 11:22 UTC, koalex approved these changes

2022-11-13 11:23 UTC, merged